replicaCount: 1
image:
  repository: jcr.nguiland.org/docker-local/com.optimagrowth/gateway-service
  pullPolicy: Always
  tag: 0.0.1-SNAPSHOT
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ''
podAnnotations:
  appCommitId: baa01583e17f611dfd5fde7efa47b86157336d88
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  failureThreshold: 5
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  failureThreshold: 5
  initialDelaySeconds: 10
  periodSeconds: 10
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: SPRING_CLOUD_CONFIG_URI
    value: http://config-service:8080
  - name: EUREKA_URI
    value: http://eureka-service:8080/eureka
  - name: JWT_ISSUER_URI
    value: https://devkeycloak.nguiland.org/realms/ostock
